import assert from 'node:assert/strict';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createWorkflow} from '../server/workflow.js';
const dir=await mkdtemp(join(tmpdir(),'crew-workflow-'));
const wait=async(w,id,status)=>{for(let i=0;i<200;i++){const p=(await w.snapshot()).projects.find(p=>p.id===id);if(p.status===status)return p;await new Promise(r=>setTimeout(r,5));}throw Error('Timed out '+status);};
const file=join(dir,'projects.json'),w=await createWorkflow({file,delay:1});
let p=await w.create({goal:'Draft a launch campaign',context:'Coffee shop, local audience'});
await assert.rejects(w.act(p.id,'approve',{version:p.version}),/review|changed/);
p=await wait(w,p.id,'needs_review');assert.equal(p.stages.filter(s=>s.status==='complete').length,3);assert.match(p.final,/DRY RUN/);assert.equal((await w.snapshot()).projects.filter(p=>p.status==='approved').length,0);
await assert.rejects(w.act(p.id,'approve',{version:1}),/changed/);
p=await w.act(p.id,'revise',{version:p.version,comment:'Make it shorter'});p=await wait(w,p.id,'needs_review');assert.equal(p.round,2);assert.equal(p.history.length,2);assert.match(p.final,/Make it shorter/);
p=await w.act(p.id,'approve',{version:p.version});assert.equal(p.status,'approved');assert.equal(JSON.parse(await readFile(file,'utf8'))[0].status,'approved');
const restored=await createWorkflow({file,delay:1});assert.equal((await restored.snapshot()).projects[0].final,p.final);
let calls=0;const questions=await createWorkflow({file:join(dir,'questions.json'),provider:async()=>++calls===1?{status:'needs_input',text:'Who is the audience?'}:{status:'complete',text:'Verified draft'}});let q=await questions.create({goal:'Write a draft'});q=await wait(questions,q.id,'needs_input');await questions.act(q.id,'answer',{version:q.version,answer:'Local customers'});q=await wait(questions,q.id,'needs_review');assert.match(q.context,/Local customers/);
let fail=true;const errors=await createWorkflow({file:join(dir,'errors.json'),provider:async()=>{if(fail)throw Error('secret');return{status:'complete',text:'Draft'};}});let e=await errors.create({goal:'Try a draft'});e=await wait(errors,e.id,'error');assert.doesNotMatch(e.stages[0].error,/secret/);fail=false;await errors.act(e.id,'retry',{version:e.version});await wait(errors,e.id,'needs_review');
let requests=[];const live=await createWorkflow({file:join(dir,'live.json'),dryRun:false,key:'test-only',fetchImpl:async(url,options)=>{requests.push(JSON.parse(options.body));return{ok:true,json:async()=>({content:[{type:'text',text:JSON.stringify({status:'complete',text:'Mocked output'})}]})};}});const l=await live.create({goal:'Mock API adapter'});await wait(live,l.id,'needs_review');assert.equal(requests.length,3);assert.equal(JSON.parse(requests[1].messages[0].content).previousStages[0].output,'Mocked output');
console.log('PASS: handoffs, review gate, revisions, stale actions, persistence, questions, retry and mocked Claude adapter. No paid calls.');
